{% set version = "0.1.1" %}

package:
  name: velocypack
  version: {{ version }}

source:
  url: https://github.com/gdmiron/velocypack/archive/v{{ version }}.tar.gz
  sha256: c22edf1212bd0b59feabea995011705b9fd02ba08b2bff12956e8c58b1279ef4

build:
  number: 0
  skip: True  # [win and vc<14]

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - ninja  # [win]
    - make  # [unix]
    - make  # [osx]

test:
  commands:
    - test -d ${PREFIX}/include/velocypack  # [unix]
    - test -f ${PREFIX}/include/velocypack/vpack.h  # [unix]
    - if exist %LIBRARY_PREFIX%\include\velocypack\vpack.h (exit 0) else (exit 1)  # [win]

about:
  home: https://github.com/arangodb/velocypack
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: A fast and compact format for serialization and storage
  doc_url: https://github.com/arangodb/velocypack
  dev_url: https://github.com/arangodb/velocypack

extra:
  recipe-maintainers:
    - gdmiron
